version: "3.8"

services:
  backend:
    image: ghcr.io/ostemadprinsesse/dinner-served-backend:latest
    container_name: dinner-served-backend
    restart: unless-stopped
    environment:
      - DB_PATH=/app/data/app.db
    volumes:
      - sqlite-data:/app/data
    networks:
      - dinner-network

  frontend:
    image: ghcr.io/ostemadprinsesse/dinner-served-frontend:latest
    container_name: dinner-served-frontend
    restart: unless-stopped
    ports:
      - "80:3005"
    environment:
      - NEXT_PUBLIC_BASE_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - dinner-network

volumes:
  sqlite-data:
    name: dinner-served-sqlite

networks:
  dinner-network:
